### ISSUE TITLE
拜读大作，深表敬佩

### ISSUE THREAD

**Issue by cogitoergosum666** [PKUFlyingPig/pkuflyingpig.github.io#1]
但目前登录https://pkuflyingpig.github.io/pku-cs-self-learning/已经404了，这是暂时的还是永久的呢？
顺颂时祺

**Comment by PKUFlyingPig** [comment]
链接已迁移到https://pkuflyingpig.github.io/cs-self-learning/，对给您带来的不便深感抱歉。
